networks:
  userTesting:
      driver: bridge

services:
  usertesting-api:
    image: usertesting-api
    build:
      context: .
      dockerfile: UserTestingAPI/Dockerfile
    depends_on:
      usertesting-db:
        condition: service_healthy
    ports:
      - "5000:80"
    networks: 
      - userTesting
    restart: always
      
  usertesting-db:
    image: postgres:15.0
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userTesting
    container_name: usertesting-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - userTesting
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres-user -d userTesting" ]
      interval: 10s
      timeout: 3s
      retries: 3