networks:
  userTesting:
      driver: bridge

services:
  usertestingapi:
    image: userTestingApi
    build:
      context: .
      dockerfile: UserTestingAPI/Dockerfile
    depends_on: usertestingDb
    ports:
      - "5000:80"
    networks: 
      - userTesting
  usertestingDb:
    image: postgres:15.0
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userTesting
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - userTesting
